version: "3"
services:
  portainer: 
    image: portainer/portainer-ce
    container_name: portainer
    network_mode: bridge
    restart: always
    ports: 
      - "8000:8000"
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    network_mode: bridge
    restart: always
    volumes: 
      - /srv/proxy/ssl:/etc/nginx/certs
      - /srv/proxy/vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    ports: 
      - "80:80"
      - "443:443"

  leresolver:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: leresolver
    volumes_from: 
      - proxy
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=mateusz.kilinski@gmail.com

  
volumes:
    portainer_data: {}