version: "3"
services:
  template_db: 
    image: mysql:latest
    container_name: template_db
    network_mode: bridge
    restart: always
    volumes: 
      - template_db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=abc123
  
  template_pma:
    image: phpmyadmin
    container_name: template_pma
    network_mode: bridge
    environment: 
      - UPLOAD_LIMIT=64M
      - PMA_ABSOLUTE_URI=https://hostname/pma/
    links: 
      - "template_db:db"
    depends_on: 
      - template_db

  template_web:
    build: .
    container_name: template_web
    network_mode: bridge
    volumes: 
      - template_data:/srv
    depends_on: 
      - template_pma
      - template_db
    links: 
      - template_db:db
      - template_pma:pma
    environment:
      - VIRTUAL_HOST=hostname
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=hostname
volumes:
    template_data: {}
    template_db: {}